<?php foreach ($cats as $key => $cat): ?>

    <?php if ($key%2 != 0): ?>
        <section class="left">

            <article class="flexslider">
                <ul class="slides">
                    <?php foreach ($cat['images'] as $image): ?>
                        <li>
                            <img src="www/img/<?= $image['image_url']?>" alt="<?= $image['alt_img'] ?> "/>
                        </li>
                    <?php endforeach ?>
                </ul>
            </article>

            <article>
                <h2><?= $cat['title'] ?></h2>
                <?= $cat['presentation'] ?>
            </article>

        </section>

    <?php else: ?>
        <section class="right">

            <article class="flexslider">
                <ul class="slides">
                    <?php foreach ($cat['images'] as $image): ?>
                        <li>
                            <img src="www/img/<?= $image['image_url']?>" alt="<?= $image['alt_img'] ?> "/>
                        </li>
                    <?php endforeach ?>
                </ul>
            </article>

            <article>
                <h2><?= $cat['title'] ?></h2>
                <?= $cat['presentation'] ?>
            </article>

        </section>
    <?php endif ?>

<?php endforeach ?>
