<section  class="content flex form">

        <form method='POST' >
            <fieldset>
                <legend>Contactez-nous</legend>
                <label><input type="text" name="firstname" placeholder="Votre prénom"></label>
                <label><input type="text" name="email" placeholder="Votre mail"></label>
                <label class="textarea"><textarea name="message" placeholder="Votre message"></textarea></label>
                <button type="submit" name="envoyer">Envoyer</button>
            </fieldset>
        </form>

</section>