<section class="form">
    <form method="post">
        <fieldset>
            <legend>Connexion</legend>
            <ul>
                <li>
                    <label for="mail">
                        Adresse mail :
                        <input type="text" name="email" placeholder="aaa@aaa.aa" id="mail">
                    </label>
                </li>
                <li>
                    <label for="password">
                        Mot de Passe :
                        <input type="password" name="password" placeholder="Mot de passe" id="password">
                    </label>
                </li>
            </ul>
            <button type="submit" name="connexion" value="Valider">valider</button>
        </fieldset>


    </form>
</section>