<section class="form">
    <form method="post">
        <fieldset>
            <legend>Informations Personelles</legend>
            <ul>
                <li>
                    <label for="lastName">
                        Nom :
                        <input type="text" name="lastName" placeholder="Nom" id="lastName">
                    </label>
                </li>
                <li>
                    <label for="firstName">
                        Prénom :
                        <input type="text" name="firstName" placeholder="Prenom" id="firstName">
                    </label>
                </li>
                <li>
                    <label for="mail">
                        Adresse mail :
                        <input type="text" name="email" placeholder="aaa@aaa.aa" id="mail">
                    </label>
                </li>
                <li>
                    <label for="password">
                        Mot de Passe :
                        <input type="password" name="password" placeholder="Mot de passe" id="password">
                    </label>
                </li>

            </ul>
            <button type="submit" name="inscription" value="Valider">valider</button>
        </fieldset>


    </form>
</section>